sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
  - '10'
  - '12'
install: npm install
script: npm run test && npm run build
after_success: travis-after-success
branches:
  only: master